services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SPRING_PROFILE=dev
    image: webrtc-demo:latest
    ports:
      - "8989:8989"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./src/main/resources:/deployments/resources/main
    restart: unless-stopped